{% set name = "neovim-remote" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neovim-remote-{{ version }}.tar.gz
  sha256: f199ebb61c3decf462feed4e7d467094ed38d8afaf43620736b5983a12fe2427

build:
  number: 0
  noarch: python
  entry_points:
    - nvr = nvr.nvr:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - psutil
    - pynvim
    - python >=3.5
    - setuptools

test:
  imports:
    - nvr
  commands:
    - pip check
    - nvr --help
  requires:
    - pip

about:
  home: https://github.com/mhinz/neovim-remote
  summary: Control nvim processes using "nvr" commandline tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pdiercks
